CREATE TABLE TEST_TABLE
(
    TEST_INT_COLUMN INTEGER,
    TEST_TEXT_COLUMN TEXT,
    TEST_DATE_COLUMN DATE
);

DO $$
BEGIN
    FOR r IN 1..100000
    LOOP
        INSERT INTO TEST_TABLE (TEST_INT_COLUMN, TEST_TEXT_COLUMN, TEST_DATE_COLUMN) VALUES (r, 'test_text', current_date);
    END LOOP;
END $$;