CREATE SEQUENCE test_table_id_seq;

CREATE TABLE TEST_TABLE
(
    ID INTEGER NOT NULL DEFAULT nextval('test_table_id_seq'),
    TEST_INT_COLUMN INTEGER,
    TEST_TEXT_COLUMN TEXT,
    TEST_DATE_COLUMN DATE
);

ALTER SEQUENCE test_table_id_seq OWNED BY TEST_TABLE.ID;

DO $$
BEGIN
    FOR r IN 1..100000
    LOOP
        INSERT INTO TEST_TABLE (TEST_INT_COLUMN, TEST_TEXT_COLUMN, TEST_DATE_COLUMN) VALUES (r, 'test_text', current_date);
    END LOOP;
END $$;